hq parser application WIP
It4innovations/hyperqueue pull request #120
Opened 2021-08-07 07:28 UTC by User3574

Fixes: #52

2021-08-07 20:26 UTC, Kobzol approved these changes

2021-08-07 20:26 UTC, Kobzol commented on src/bin/hq.rs
> +    selector_arg: SelectorArg,
Please add a doc comment (`///`) to there arguments so that users know what they represent.

2021-08-07 20:26 UTC, Kobzol commented on src/common/arraydef.rs
> +    pub fn count_ids(&self) -> u32 {
```suggestion
    pub fn id_count(&self) -> u32 {
```

2021-08-07 20:26 UTC, Kobzol commented on src/common/arraydef.rs
> +    pub fn get_ids(&self) -> Vec<u32> {
This shouldn't be needed, users can just call `iter()` and then collect the result into whatever they want.

2021-08-07 20:26 UTC, Kobzol commented on src/server/client.rs
> +            .get_ids()
```suggestion

```

2021-08-07 20:26 UTC, Kobzol commented on tests/test_worker.py
> +    wait_for_worker_state(hq_env, [1, 2, 3], ["RUNNING" for i in range(3)])
`["RUNNING" for i in range(3)]` can be written more succintly as `["RUNNING"] * 3`.
But here it's enough to just specify `"RUNNING"` as the last argument, it's converted internally to a set anyway.

2021-08-10 09:36 UTC, Kobzol approved these changes

2021-08-10 12:44 UTC, spirali requested changes

2021-08-10 12:44 UTC, spirali commented on src/server/client.rs
> +            .map(|job_info| job_info.id)
These to maps could by written just as ``.map(|job| job.job_id)`` without creating job info

2021-08-11 07:34 UTC, Kobzol approved these changes

2021-08-11 07:34 UTC, Kobzol commented on src/server/client.rs
> +            responses.push((job_id, Option::from(detail)));
```suggestion
            responses.push((job_id, Some(detail)));
```

2021-08-11 07:34 UTC, Kobzol commented on src/server/client.rs
> +            responses.push((job_id, Option::None));
```suggestion
            responses.push((job_id, None));
```

2021-08-11 09:32 UTC, merged