ENH: create all folder given from user defined stdout and stderr file path
It4innovations/hyperqueue pull request #122
Opened 2021-08-10 11:06 UTC by fredykoci

2021-08-10 12:52 UTC, Kobzol requested changes

2021-08-10 12:52 UTC, Kobzol commented on src/worker/start.rs
> +        std::fs::create_dir_all(std_folders)?;
You can pass `PathBuf` to `create_dir_all` directly. Try something like
```rust
if let StdioDef::File(path) = program.stdout {
    std::fs::create_dir_all(path)?;
}
```
Please also do the same for `stderr`.

2021-08-10 13:32 UTC, Kobzol requested changes

2021-08-10 13:32 UTC, Kobzol commented on src/worker/start.rs
> +
I would suggest to rewrite it slightly to remove the useless else branches. And also rename it, the current name is not very descriptive.
```rust
fn create_directory_if_needed(file: &StdioDef) -> io::Result<()> {
    if let StdioDef::File(path) = file {
        if let Some(path) = path.parent() {
            std::fs::create_dir_all(path)?;
        }
    }
    Ok(())
}
```

2021-08-10 14:12 UTC, Kobzol approved these changes

2021-08-12 14:09 UTC, spirali reviewed
Look good.
Next steps: 

* Remove all warnings
* Update user documentation
* Update changelog.md

2021-08-16 12:08 UTC, Kobzol commented
Rebased over master for merge. @fredykoci thanks!

2021-08-16 12:08 UTC, merged