Filtering
It4innovations/hyperqueue pull request #292
Opened 2022-01-11 15:37 UTC by fredykoci

2022-01-13 07:53 UTC, Kobzol requested changes

2022-01-26 11:05 UTC, Kobzol requested changes

2022-01-26 11:05 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
> +fn lost_worker_info_to_str(worker: &WorkerInfo) -> String {
These functions are not needed.

2022-01-26 11:05 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
> +        workers.sort_unstable_by_key(|w| w.id);
Let's sort the workers always, before we return them from the function.

2022-01-26 11:05 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
>      include_offline: bool,
`include_offline` is no longer needed, this function should just take `connection` and `filters: Set<WorkerFilter>`.

2022-01-26 11:05 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
> +    All,
Let's remove the `All` variant, it's not needed and it doesn't make sense to use e.g. `--filter all,running`. If the filter set will be empty, all workers will be returned.

2022-01-27 08:08 UTC, fredykoci commented on crates/hyperqueue/src/client/commands/jobs.rs
> +        response.jobs.retain(|j| {
this is the reason why this PR starts

2022-01-27 08:38 UTC, Kobzol requested changes

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/bin/hq.rs
> +        multiple_occurrences(false)
These three options are now not needed.

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/bin/hq.rs
> +    /// Flag to list offline workers
Please keep the original help message.

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/bin/hq.rs
> +#[clap(author, about, version(option_env ! ("HQ_BUILD_VERSION").unwrap_or(env ! ("CARGO_PKG_VERSION"))))]
Formatting change.

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
> +                "Invalid worker filter value '{}'. Allowed values are 'all', 'running' or 'offline'.",
```suggestion
                "Invalid worker filter value '{}'. Allowed values are 'running' or 'offline'.",
```

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/client/commands/worker.rs
>      include_offline: bool,
```suggestion

```
This parameter should be removed. If `--all` nor `--filter` is entered, the command code should pass `Some(WorkerFilter::Running)`.

2022-01-27 08:38 UTC, Kobzol commented on crates/hyperqueue/src/transfer/messages.rs
> +#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
```suggestion
#[derive(Serialize, Deserialize, Debug, Clone)]
```

2022-02-02 14:56 UTC, merged