Filter online offline workers
It4innovations/hyperqueue pull request #38
Opened 2021-05-21 11:35 UTC by fredykoci

2021-05-21 11:54 UTC, Kobzol requested changes
With this implementation, if the user passes neither `running` nor `offline`, no workers will be shown.
Maybe it would be better to only implement a single flag (`--online`) with the following behaviour:
1) If nothing is passed, all workers will be displayed
2) If `--online` is passed, only online workers will be displayed

2021-05-21 11:54 UTC, Kobzol commented on src/bin/hq.rs
> +    }
```rust
let workers_to_print: Vec<_> = workers
    .iter()
    .filter(|worker| worker_state(worker, &opts)
    .collect();
```

2021-05-21 11:54 UTC, Kobzol commented on src/bin/hq.rs
> +fn worker_state(worker:&WorkerInfo,option:&WorkerListOpts) -> bool{
I would rename this to something like `should_be_printed`.

2021-05-22 08:03 UTC, spirali requested changes

2021-05-22 08:03 UTC, spirali commented on src/bin/hq.rs
> +        .await.unwrap();
Do not use unwrap but propagate the error (via ``?`` operator)

2021-05-22 08:03 UTC, spirali commented on src/client/commands/worker.rs
> +) -> crate::Result<(Vec<WorkerInfo>)> {
Superfluous parenthesis

2021-05-22 08:50 UTC, spirali commented
Please include also Python integration tests in your code (directory "tests").

2021-05-27 08:12 UTC, spirali commented
I have rebased and squashed your commits as c9e6523d6806a36ef461db5efa1c5f5d23db719b.
I have also added a small refactoring 7144980369a5a747b029ff5710e304dab59e719e, if you have any question to my changes, do not hesitate to ask.

Thank you for your work.

2021-05-27 08:12 UTC, closed without merging