Task list output verbosity
It4innovations/hyperqueue pull request #444
Opened 2022-06-24 07:45 UTC by User3574

Closes: #426

2022-06-24 10:18 UTC, Kobzol commented
For Unix tools it's common to select verbosity with short flags (`-v`, `-vv`, `-vvv`). I tried to look at how it can be done using `clap`, but it was a bit complicated, so I took the implementation from https://docs.rs/clap-verbosity-flag/latest/clap_verbosity_flag/ and implemented it here.

The default should be brief verbosity, otherwise it's not very useful, and it couldn't be disabled anyway with the short flags.

Could you please fix tests? They will need to use the verbose mode. Thanks.

2022-06-24 13:13 UTC, Kobzol requested changes

2022-06-27 07:38 UTC, Kobzol commented
When the error is hidden, it might be confusing to the user, since we hide important information from him. Maybe it would be better if we always shown the error column, but if the output mode is not verbose, we truncate it. I suggest to truncate the error if it's longer than `X` (16) characters or if it contains a newline.

Then we should show some message that says "Use -v to display full error.", and place it either below the table or in the error column. @spirali thoughts?

2022-06-27 08:36 UTC, spirali commented
> When the error is hidden, it might be confusing to the user, since we hide important information from him. Maybe it would be better if we always shown the error column, but if the output mode is not verbose, we truncate it. I suggest to truncate the error if it's longer than `X` (16) characters or if it contains a newline.
> 
> Then we should show some message that says "Use -v to display full error.", and place it either below the table or in the error column. @spirali thoughts?

It seems like a good idea: hame some small fragment by default and full info by "-v".

2022-07-04 09:45 UTC, Kobzol requested changes

2022-07-04 09:45 UTC, Kobzol commented on crates/hyperqueue/src/client/output/cli.rs
> +        log::info!("Use -v to display full error.");
```suggestion
        log::info!("An error message was truncated. Use -v to display the full error.");
```
+ only print this if at least one error was actually truncated.

2022-07-04 09:45 UTC, Kobzol commented on crates/hyperqueue/src/client/output/cli.rs
> +                                        error_mut = error_mut.add("...");
```suggestion
                                        error_mut.push_str("...");
```

2022-07-07 07:04 UTC, Kobzol commented
Great! :) Please rebase on master & squash commits and I'll merge it.

2022-07-11 09:09 UTC, Kobzol approved these changes

2022-07-11 09:09 UTC, merged