added priority subcommand
It4innovations/hyperqueue pull request #77
Opened 2021-06-23 12:04 UTC by Dotnester

2021-06-23 12:22 UTC, Kobzol commented
Looks fine :) Please rebase over `main` to resolve conflicts and add documentation to `docs/jobs.md`.

You can build the documentation locally using `mkdocs serve`. You can install mkdocs in Python:
```
$ python3 -m pip install mkdocs
$ python3 -m mkdoc serve
```

2021-06-24 17:11 UTC, spirali commented
Code looks good, please add tests as we have discussed. If it is too complicated I can resolve conflicts myself

2021-07-27 08:18 UTC, Kobzol requested changes

2021-07-27 08:18 UTC, Kobzol commented on tests/test_job.py
> +            "echo `date` && sleep 1",
```suggestion
            "date --iso-8601=seconds && sleep 1",
```

2021-07-27 08:18 UTC, Kobzol commented on tests/test_job.py
> +            dates.append(int(parts[2][0])*10+int(parts[2][1]))
```suggestion
            dates.append(datetime.fromisoformat(f.read().strip()))
```

2021-07-27 11:21 UTC, merged

2021-07-27 11:21 UTC, Kobzol commented
@Dotnester thanks!